# Generated by Django 6.0.4 on 2026-04-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
